language: java
dist: trusty
jdk:
  - oraclejdk8

stages:
  - compile
  - test

branches:
  only:
  - master

jobs:
  include:
    - stage: compile
      script: mvn clean package -Dmaven.test.skip=true
    - stage: test
      script: mvn cobertura:cobertura -Dmaven.test.skip=false -Dtest=**/value/**.java

after_success:
  - bash <(curl -s https://codecov.io/bash)
